### PR TITLE
Make gpio.py handle wide (16-bit) GPIO ports

### PR DESCRIPTION
**Pull request by sgoadhouse**
I took the code from spi.py that handles wide, 16-bit GPIO and moved it over to the gpio.py GpioController. It is done in a way that if the device supports wide gpio, then it opens it as a MPSSE and handles it accordingly. Otherwise, if not wide, it uses the old biting method.

### CODE REVIEW

**Comment by eblot** [comment]
See nice, I still lack time to create an setup up and test it :-(

I would suggest to replace the commented print lines with a logger - as there's also one with `pyftdi.ftdi`, something like "pyftdi.gpio" would be nice, I guess.

**Comment by eblot** [comment]
Would you have any test which exercise GPIO 8 & GPIO 16 bit modes?
For example GPIO AD0..AD3 (output) connected to GPIO AD4..AD7 (input) and GPIO AC0..AC3 (input), as least for a basic test?

**Comment by sgoadhouse** [comment]
That is a really good idea. Sorry I did not think about it. I sort of put it together while working with a device. I tested it both on a FT232H (16-bit GPIO) and FT4232H (8-bit GPIO). Good thing I tested it.

I will add the logger and submit again.

Sent from my iPad

On Jun 22, 2018, at 08:58, Emmanuel Blot <notifications@github.com<mailto:notifications@github.com>> wrote:


See nice, I still lack time to create an setup up and test it :-(

I would suggest to replace the commented print lines with a logger - as there's also one with pyftdi.ftdi, something like "pyftdi.gpio" would be nice, I guess.

**Comment by sgoadhouse** [comment]
Okay, I have updated to use logging. I have tested on my system but it is not an automated test like the one you suggested.

**Comment by copercini** [comment]
Testing here with a FT2232H, with this config:
```
out_pins &= 0xE003 # Out, Out, Out, In, In, In, In, In,  In, In, In, In,  In, In, Out, Out
url = environ.get('FTDI_DEVICE', 'ftdi://ftdi:2232h/1')
self._gpio.open_from_url(url, direction=out_pins)
```
it gives this error using your PR, no problems without it 
```
  File "esp_factorytest.py", line 474, in <module>
    main()
  File "esp_factorytest.py", line 410, in main
    gpio.open(mask)
  File "esp_factorytest.py", line 61, in open
    self._gpio.open_from_url(url, direction=out_pins)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\pyftdi\gpio.py", line 102, in configure
    ftdi.open_mpsse_from_url(url, direction=direction, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\pyftdi\ftdi.py", line 475, in open_mpsse_from_url
    direction, initial, frequency, latency, debug)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\pyftdi\ftdi.py", line 539, in open_mpsse
    self.write_data(array('B', (Ftdi.SET_BITS_LOW, initial, direction)))
OverflowError: unsigned byte integer is greater than maximum
```

**Comment by copercini** [comment]
@sgoadhouse do you have some example of how init it with 16 bits instead 8?

**Comment by copercini** [comment]
worked with:

```
def test():
    #Open GPIO
    gpio = GpioTest()
    mask = 0xFF  # Out, Out, Out, Out, Out, Out, Out, Out
    gpio.open(mask)
    gpio.set_direction(0xFFFF, 0xFFFF) # set all 16 pins as output
    gpio.set_gpio(14, True)
````

**Comment by sgoadhouse** [comment]
Sorry I am delayed in responding.  Is everything working now for you? I see you figured that all you need is to supply a 16 bit number and the upper byte is operational. I thought there was an example somewhere but it appears that the example is in a different project of mine that uses this update.



--
Stephen Goadhouse
Electronics Engineer

University of Virginia
Physics Department
office: room 265
434-982-5594
sgoadhouse@virginia.edu<mailto:sgoadhouse@virginia.edu>
http://faculty.virginia.edu/phys-electronics<http://faculty.virginia.edu/phys-electronics/>

For any Electronics Shop requests, please email the team at phys-electronics@Virginia.EDU<mailto:physics-electronics-shop@Virginia.EDU>
or feel free to come see Larry St. John in the Electronics Shop in Physics Rm 115


On July 26, 2018 at 12:40:19 PM, copercini (notifications@github.com<mailto:notifications@github.com>) wrote:

worked with:

def test():
    #Open GPIO
    gpio = GpioTest()
    mask = 0xFF  # Out, Out, Out, Out, Out, Out, Out, Out
    gpio.open(mask)
    gpio.set_direction(0xFFFF, 0xFFFF) # set all 16 pins as output
    gpio.set_gpio(14, True)

**Comment by eblot** [comment]
Finally implemented in v0.49.0. Thanks and very sorry for the delay.

**Pull request closed without merging**
