### PR TITLE
GPIO in I2C fixes

### PR DESCRIPTION
**Pull request by TedKus**
In this branch I worked on the I2C module and use of GPIO.
_gpio_mask was made a permanent fixture (after all they don't change) 
_gpio_last was added to keep track of users last state for the pins
immediate was added to set_direction so that a change of in to out or out to in would take effect immediately (new default behavior) 
with_input added to write to allow "writes" to gpio's set as inputs, which is useful for open-drain behavior when combined with gpio_last (new default behavior).  This suppresses an error message that used to occur, but since no reasonably functional code would be looking for an error it should work for everyone.
This version should be backwards compatible with any existing code.
Also tried to more completely add the reset/freeze options for opening/closing the device but my testing with this was inconclusive and I have to move on.  I2C works fine, but gpios' would not work if reset=False.  There might be more to come on this as it's an interesting idea.
Tested with C232HM-EDHSL-0

### CODE REVIEW

**Comment by TedKus** [comment]
Also it appears i didn't make this as a new branch and some older commits are still in there.  I can retract this and make a new one properly if needed.

**Comment by TedKus** [comment]
I found a shortcoming with my original fix, and added a commit to init _gpio_last from the kwargs.
In the prior code without init of _gpio_last, it could bomb out if the user attempted to change a tri-state setting before driving the gpio states with a write.  oops.

**Comment by eblot** [comment]
I'm no longer able to understand the proposed PR.
I have no real time to test it, but I think it would nevertheless be useful.

Could you close this PR and open a new one with logical change sets in each commit, so I can review it? Thanks a lot.

**Comment by eblot** [comment]
> I'm no longer able to understand the proposed PR. 

*i.e.* https://github.com/eblot/pyftdi/pull/260/files seems to contains already existing code in master...

**Comment by TedKus** [comment]
Absolutely.  I'll close this and make only the targeted changes.  my bad for not catching the lack of a branch.

**Pull request closed without merging**
