### PR TITLE
Add support for simultaneous I2C and GPIO usage in i2c.py

### PR DESCRIPTION
**Pull request by meierphil**
Introduce class 'I2cGpioPort' analogous to 'SpiGpioPort' in spi.py.
Refactor all spi to i2c.

Copy and adapt all GPIO related methods from 'SpiController' to
'I2cController'.

In class 'I2cController', make all command sets that are supposed to write
the LSB GPIO more dynamic, i.e. property. This is necessary to avoid over-
riding the current output of the LSB GPIOs. For this purpose, introduce a
property 'self.gpio_out_data' to monitor the current output state of the
GPIOs. It makes use of the private 'self._out_data' which is only updated
when 'self._write_raw()' is called.

Add some rudimentary thread-safety using a lock in 'I2cController' similar
to 'SpiController'.

### CODE REVIEW

**Comment by meierphil** [comment]
Hi all
This is my first GitHub contribution. If I didn't stick to any convention it is probably simply nescience!

I successfully tested the commit using Python 3.6.4 on Win10 using FTDI FT232H (except thread safety).

Cheers

**Comment by meierphil** [comment]
Hi, thanks.

Sure can I. I will try to write some unit tests in the next few days.

**Comment by mprt** [comment]
any news on this?
anything I can do?

**Comment by meierphil** [comment]
Hi,
sorry for my long lasting silence on this. Apparently, I boasted in my last post. Since I never used unit tests so far, I have to work myself into that topic first.
However, the I2C GPIO support I proposed here is operational in our environmental measurement system since 1 year without issues.
I will try to keep up with unit tests in September 2019. Keep reminding me, if nothing happens.
Thanks.

**Comment by Engenia** [comment]
Hello meierphil & eblot,
I have be working with an FT232H to test I2C coms with a MSP430 slave (which uses clock stretching) and I also need to use GPIO to set certain conditions on that unit. The work done with pulse stretching last year was a godsend which works beautifully on my Ubuntu 14.04 box.

To get gpio access I asked a colleague to copy the relevant code from the gpio enhanced spi,py to the latest i2c.py. I noticed some mask issues (D7 used for pulse stretching) and rectified them.
When I first installed pyftdi.py I used
$ pip3 install pyftdi
which worked fine and allowed me to develop the clock stretched I2C scripts I needed

This time I had to install from source, substituting my i2c.py file for that from the git repository, which was a new experience for me.
When testing the new library with my previously fine script I found that there was an issue with a line in i2c.py
"from threading import lock"
A grep -i -r search for lock revealed "lock" in i2c.py and "Lock" in spi.py
I'm very new to Python, but I think lock & Lock are not equivalent.
So I changed lock to Lock, built then installed it and the problem went away

I can only assume that the file i2c.py in the repository retains an earlier error in using "lock" instead of "Lock" that was corrected in the package that pip3 uses.

**Comment by eblot** [comment]
> This time I had to install from source, substituting my i2c.py file for that from the git repository, which was a new experience for me.
It's a bit confusing: which git version are you referring to? meierphil's? A new PyFtdi version?

**Comment by Engenia** [comment]
Sam said that he "simply manually merged all the lines that are changed in the meierphil branch into the master branch of i2c.py.". I gave him the link to meierphils branch (https://github.com/meierphil/pyftdi/blob/i2c_gpio_support/pyftdi/i2c.py). Sam gave me his merged i2c.py file.

I think I may have wasted your time though. I've looked further into the mechanics of what happened.

"Lock" doesn't appear in the master branch, but it does in meierphil's branch, and not as "lock". It appears that the letter substitution happened in Sam's merge, not in either repositories. That I can't explain.

My apologies.

For what it's worth, I now have PyFtdi (i2c.py) working with both I2C clock stretching and GPIO on D4-6, and C0-7, but not C8-9. I haven't created a new branch for it though, as I haven't looked at how that is done. Like I said, I'm very new to Python, and git.

Thanks to you and meierphil for your great work.

**Comment by eblot** [comment]
> My apologies.

No problem.
I left this PR for too long and it is now hard to merge, so I'm rewriting based on @meierphil work.

I do not know if I will have time to test it extensively, so for now it will be managed in a dedicated branch.

**Comment by eblot** [comment]
> I left this PR for too long and it is now hard to merge, so I'm rewriting based on @meierphil work.

New version available in `i2c_gpio` branch. If someone wants to give it a try...

**Comment by eblot** [comment]
I've reworked the code to fit with the latest PyFtdi version, now available in [v0.30.0](https://github.com/eblot/pyftdi/releases/tag/v0.30.0).

Thanks to @meierphil for the initial implementation and to @Engenia for reviving this thread.

**Comment by meierphil** [comment]
Great work! Thanks to @eblot and @Engenia to finish what I started. I will test it in my environment, soon!

**Pull request closed without merging**
