### PR TITLE
Multiple adapters fixes

### PR DESCRIPTION
**Pull request by dgarnier**
Due to inconsistent ordering of parameters in the various open calls with ftdi.py, it was impossible to open an adapter by serial number, or by index.  This patch makes all calls with the order of parameters as would be found in the URL.

### CODE REVIEW

**Comment by eblot** [comment]
This change would break the API, but as I recently broke it with moving to Py3/PySerial3, it might be the right time to fix this. It indeed make more sense to move the interface selector after the device selectors.

However, we definitely need to update the version so that clients that rely on the API may detect API break (and fix related projects such as [pyspiflash](https://github.com/eblot/pyspiflash) and [pyi2cflash](https://github.com/eblot/pyi2cflash))

**Comment by dgarnier** [comment]
I bumped the version in the pull request indicating the API change.   Looks to me like pyspiflash is already broken.. and not made worse.  (The configure call is using individual values, but SpiController is now using a URL configure).  pyi2cflash is using the URL call.. and should be fixed with this change.

**Comment by eblot** [comment]
Ok thanks.

It think the problem with pyspiflash is that the Py3 branch has not yet been merged into the master branch, and use the old implementation.

I try to fix all this mess by these days :-)

**Comment by eblot** [comment]
Merged (and author list updated).
Thanks.

**Pull request merged**
