### PR TITLE
Add methods to SpiPort to change SPI mode

### LINKED ISSUE #106: Switching between SPI modes on one port
I'm trying to use an FT232H to control a [device](http://www.analog.com/media/en/technical-documentation/data-sheets/hmc833.pdf) that uses SPI mode 3 for writes and mode 1 for reads (both with the same chip select). Is there any existing way to do this with pyftdi? Looking at the code, it seem like I could change [this line](https://github.com/eblot/pyftdi/blob/93eb8b049287acc79e441fe2c33f9724450502b4/pyftdi/spi.py#L340) to check for chip select/mode combinations, but I'd like to avoid spinning a custom version of pyftdi if possible.

### PR DESCRIPTION
**Pull request by jspeiser**
This was tested using an FT232H connected to an HMC833LP6GE eval board. It resolves #106.

### CODE REVIEW

**Comment by jspeiser** [comment]
Any comments on whether this is an acceptable pull request? We're currently needing to install my fork on all our machines, and it would be nice to go back to using the pip-installable version.

**Comment by jspeiser** [comment]
We don't have a specific deadline (not having it merged is more of an annoyance than a problem), but getting it merged in weeks instead of in months would be preferable. Is there anything I can do to help with the testing?

Which line has an indentation issue? I'll fix it.

**Comment by eblot** [comment]
I finally merged this PR into the new PyFtdi API, it will be part of 0.41 series.

**Comment by eblot** [comment]
Implemented as abe7eb6c

**Pull request closed without merging**
