### PR TITLE
Fix #205 - I2C stop violation

### LINKED ISSUE #205: Stop violates I2C timing
Current design has data idle high until stop is sent.  When stop is sent CLK immediately goes high and SDA immediately goes low.  However, SDA should not change until after the stop hold time timing spec.
image
Most parts this does not appear to be an issue.  However, the NXP PCA9848 I2C switch will not recognize it as a stop.

Recommend changing _stop() to start with a _clk_lo_data_lo to ensure that SDA is low before posedge of CLK.
image

This ensures SDA is low for the full stop_setup period.
image

### PR DESCRIPTION
**Pull request by naushir**
Delay the SCL transition to correctly catch the SDA low->high transition.

### CODE REVIEW

**Comment by DPM-PMC** [comment]
I have verified this works on my setup.

**Comment by daveismith** [comment]
I have verified that this works on my setup as well.

**Comment by eblot** [comment]
Sorry for the very long delay to merge this fix. Thanks again.

**Comment by TedKus** [comment]
Hello:
The stop actually needs a little more finesse.  The logic analyzer you're using is tricking you in digital mode (saleae right?), look again in analog mode.

    @property
    def _stop(self) -> Tuple[int]:
        return self._clk_lo_data_hi * self._ck_hd_sta + \  # orginal line, pre 9/26/2020
               self._clk_lo_data_lo * self._ck_hd_sta + \  # now **add** this line per the fix on 9/26/2020
               self._data_lo * self._ck_su_sto + \
               self._idle * self._ck_idle

The stop as implemented today (by this fix) has a timing violation of data going low and clock going high simultaneously, (may be easier to see if the bus is not 'relaxed' relax=False):
image

So with the new line of code added, the stop timing does not have the violation:
image

Note that in logic analyzers, if the two edges appear simultaneously, you will get intermittent results as shown in https://github.com/eblot/pyftdi/issues/205.  When there is a question of timing, the analyzer needs to be set to a very high sampling rate so that timing violations can be discerned.  Remember with those things that there is an area of uncertainty around the edge.  They show it in the center of that area typically, but it may be that the Saleae is showing it aligned to some other clock domain.

**Pull request merged**
